language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

script:
  #- mvn -Dremote.user=$REMOTE_USER  -Dremote.password=$REMOTE_PW tomcat7:deploy
  # Verify that we have a deployed project
  #- mvn verify -PACCEPT_TEST

after_success:
  - mvn tomcat7:deploy -Pdeployremote
  

notifications:
 on_failure: always
