/* Esben; DECK-CS */
package utility;

import com.google.gson.Gson;
import data.CarsFacade;
import data.LocationsTimeFacade;
import entity.Cars;
import entity.LocationsTime;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * @author Esben All rights belong to respective contributors.
 */
public class DBFiller {

    String data = "[{\"name\":\"venenatis turpis\",\"distDriven\":52303,\"brand\":\"Saab\",\"model\":\"9-3\",\"price\":940,\"comments\":\"phasellus in\",\"createdAt\":2013},\n"
            + "{\"name\":\"orci luctus\",\"distDriven\":146800,\"brand\":\"Subaru\",\"model\":\"Impreza\",\"price\":5096,\"comments\":\"ridiculus\",\"createdAt\":2018},\n"
            + "{\"name\":\"ipsum\",\"distDriven\":119594,\"brand\":\"Audi\",\"model\":\"RS4\",\"price\":3596,\"comments\":\"amet\",\"createdAt\":2010},\n"
            + "{\"name\":\"in\",\"distDriven\":31370,\"brand\":\"GMC\",\"model\":\"Yukon XL 1500\",\"price\":4149,\"comments\":\"mi pede\",\"createdAt\":2011},\n"
            + "{\"name\":\"suscipit\",\"distDriven\":46262,\"brand\":\"Chevrolet\",\"model\":\"Corvette\",\"price\":781,\"comments\":\"sit\",\"createdAt\":2014},\n"
            + "{\"name\":\"amet\",\"distDriven\":76642,\"brand\":\"Lexus\",\"model\":\"IS-F\",\"price\":677,\"comments\":\"dapibus at\",\"createdAt\":2011},\n"
            + "{\"name\":\"volutpat erat\",\"distDriven\":72448,\"brand\":\"Nissan\",\"model\":\"Altima\",\"price\":665,\"comments\":\"tincidunt\",\"createdAt\":2012},\n"
            + "{\"name\":\"lacus\",\"distDriven\":25386,\"brand\":\"Ford\",\"model\":\"E350\",\"price\":3019,\"comments\":\"cubilia\",\"createdAt\":2014},\n"
            + "{\"name\":\"nulla ultrices\",\"distDriven\":8371,\"brand\":\"GMC\",\"model\":\"Savana 3500\",\"price\":6216,\"comments\":\"ac\",\"createdAt\":2010},\n"
            + "{\"name\":\"maecenas ut\",\"distDriven\":110625,\"brand\":\"Volvo\",\"model\":\"S60\",\"price\":5252,\"comments\":\"iaculis justo\",\"createdAt\":2017},\n"
            + "{\"name\":\"potenti in\",\"distDriven\":81148,\"brand\":\"Peugeot\",\"model\":\"207\",\"price\":5877,\"comments\":\"leo\",\"createdAt\":2014},\n"
            + "{\"name\":\"nunc commodo\",\"distDriven\":43890,\"brand\":\"Volkswagen\",\"model\":\"Corrado\",\"price\":3086,\"comments\":\"at turpis\",\"createdAt\":2014},\n"
            + "{\"name\":\"pharetra\",\"distDriven\":56313,\"brand\":\"Volvo\",\"model\":\"C30\",\"price\":1518,\"comments\":\"sapien\",\"createdAt\":2012},\n"
            + "{\"name\":\"metus vitae\",\"distDriven\":53759,\"brand\":\"Mitsubishi\",\"model\":\"Mirage\",\"price\":1141,\"comments\":\"velit\",\"createdAt\":2015},\n"
            + "{\"name\":\"nullam molestie\",\"distDriven\":124674,\"brand\":\"MINI\",\"model\":\"Countryman\",\"price\":4928,\"comments\":\"donec\",\"createdAt\":2018},\n"
            + "{\"name\":\"elit\",\"distDriven\":104735,\"brand\":\"Nissan\",\"model\":\"Pathfinder\",\"price\":5713,\"comments\":\"justo\",\"createdAt\":2010},\n"
            + "{\"name\":\"eu pede\",\"distDriven\":136730,\"brand\":\"Isuzu\",\"model\":\"Rodeo\",\"price\":1714,\"comments\":\"odio\",\"createdAt\":2010},\n"
            + "{\"name\":\"ut at\",\"distDriven\":133956,\"brand\":\"Buick\",\"model\":\"Skylark\",\"price\":324,\"comments\":\"ligula sit\",\"createdAt\":2017},\n"
            + "{\"name\":\"praesent blandit\",\"distDriven\":135214,\"brand\":\"Subaru\",\"model\":\"Impreza\",\"price\":5704,\"comments\":\"massa donec\",\"createdAt\":2010},\n"
            + "{\"name\":\"potenti cras\",\"distDriven\":118321,\"brand\":\"Chevrolet\",\"model\":\"Silverado 3500HD\",\"price\":6603,\"comments\":\"nullam sit\",\"createdAt\":2010},\n"
            + "{\"name\":\"ut mauris\",\"distDriven\":21139,\"brand\":\"Suzuki\",\"model\":\"Equator\",\"price\":6230,\"comments\":\"lacinia aenean\",\"createdAt\":2017},\n"
            + "{\"name\":\"amet\",\"distDriven\":36941,\"brand\":\"Hyundai\",\"model\":\"XG350\",\"price\":1346,\"comments\":\"sit amet\",\"createdAt\":2016},\n"
            + "{\"name\":\"vehicula consequat\",\"distDriven\":54510,\"brand\":\"Subaru\",\"model\":\"Baja\",\"price\":3321,\"comments\":\"congue diam\",\"createdAt\":2016},\n"
            + "{\"name\":\"vel ipsum\",\"distDriven\":5558,\"brand\":\"Toyota\",\"model\":\"Land Cruiser\",\"price\":6288,\"comments\":\"phasellus id\",\"createdAt\":2019},\n"
            + "{\"name\":\"nonummy\",\"distDriven\":8473,\"brand\":\"Lexus\",\"model\":\"GX\",\"price\":3746,\"comments\":\"cras\",\"createdAt\":2019},\n"
            + "{\"name\":\"leo maecenas\",\"distDriven\":6349,\"brand\":\"Mitsubishi\",\"model\":\"Pajero\",\"price\":436,\"comments\":\"nec\",\"createdAt\":2019},\n"
            + "{\"name\":\"duis\",\"distDriven\":37695,\"brand\":\"Isuzu\",\"model\":\"Ascender\",\"price\":6957,\"comments\":\"id nisl\",\"createdAt\":2013},\n"
            + "{\"name\":\"aenean fermentum\",\"distDriven\":141554,\"brand\":\"Isuzu\",\"model\":\"Ascender\",\"price\":457,\"comments\":\"mauris\",\"createdAt\":2019},\n"
            + "{\"name\":\"convallis\",\"distDriven\":99476,\"brand\":\"Buick\",\"model\":\"Century\",\"price\":4171,\"comments\":\"sed tristique\",\"createdAt\":2016},\n"
            + "{\"name\":\"vel augue\",\"distDriven\":34212,\"brand\":\"Lincoln\",\"model\":\"Mark VIII\",\"price\":3714,\"comments\":\"ipsum\",\"createdAt\":2015},\n"
            + "{\"name\":\"porttitor\",\"distDriven\":76550,\"brand\":\"Dodge\",\"model\":\"Colt\",\"price\":4856,\"comments\":\"et\",\"createdAt\":2018},\n"
            + "{\"name\":\"pede\",\"distDriven\":128640,\"brand\":\"Lexus\",\"model\":\"HS\",\"price\":4761,\"comments\":\"imperdiet\",\"createdAt\":2011},\n"
            + "{\"name\":\"erat fermentum\",\"distDriven\":117956,\"brand\":\"Maserati\",\"model\":\"Quattroporte\",\"price\":6387,\"comments\":\"eu nibh\",\"createdAt\":2015},\n"
            + "{\"name\":\"scelerisque mauris\",\"distDriven\":85702,\"brand\":\"Chevrolet\",\"model\":\"Metro\",\"price\":1468,\"comments\":\"ligula\",\"createdAt\":2019},\n"
            + "{\"name\":\"venenatis tristique\",\"distDriven\":58416,\"brand\":\"Mercedes-Benz\",\"model\":\"E-Class\",\"price\":1575,\"comments\":\"eget\",\"createdAt\":2011},\n"
            + "{\"name\":\"blandit\",\"distDriven\":53545,\"brand\":\"Acura\",\"model\":\"RL\",\"price\":297,\"comments\":\"varius\",\"createdAt\":2011},\n"
            + "{\"name\":\"posuere cubilia\",\"distDriven\":36388,\"brand\":\"Subaru\",\"model\":\"SVX\",\"price\":779,\"comments\":\"at velit\",\"createdAt\":2017},\n"
            + "{\"name\":\"pulvinar\",\"distDriven\":42302,\"brand\":\"Ford\",\"model\":\"Festiva\",\"price\":4341,\"comments\":\"morbi\",\"createdAt\":2015},\n"
            + "{\"name\":\"in\",\"distDriven\":113396,\"brand\":\"Mercedes-Benz\",\"model\":\"M-Class\",\"price\":2606,\"comments\":\"sit\",\"createdAt\":2013},\n"
            + "{\"name\":\"feugiat\",\"distDriven\":100228,\"brand\":\"Chevrolet\",\"model\":\"Avalanche 2500\",\"price\":552,\"comments\":\"a\",\"createdAt\":2017},\n"
            + "{\"name\":\"ac est\",\"distDriven\":63877,\"brand\":\"Dodge\",\"model\":\"Avenger\",\"price\":3706,\"comments\":\"quis\",\"createdAt\":2019},\n"
            + "{\"name\":\"curae mauris\",\"distDriven\":21323,\"brand\":\"Land Rover\",\"model\":\"Freelander\",\"price\":6075,\"comments\":\"tortor\",\"createdAt\":2010},\n"
            + "{\"name\":\"integer non\",\"distDriven\":81585,\"brand\":\"Honda\",\"model\":\"Insight\",\"price\":6144,\"comments\":\"ante vivamus\",\"createdAt\":2012},\n"
            + "{\"name\":\"erat\",\"distDriven\":104827,\"brand\":\"Chevrolet\",\"model\":\"Aveo\",\"price\":6557,\"comments\":\"justo pellentesque\",\"createdAt\":2012},\n"
            + "{\"name\":\"vitae mattis\",\"distDriven\":45077,\"brand\":\"Honda\",\"model\":\"Passport\",\"price\":2622,\"comments\":\"a odio\",\"createdAt\":2019},\n"
            + "{\"name\":\"et ultrices\",\"distDriven\":118997,\"brand\":\"Infiniti\",\"model\":\"QX\",\"price\":6242,\"comments\":\"suscipit nulla\",\"createdAt\":2014},\n"
            + "{\"name\":\"convallis nunc\",\"distDriven\":24420,\"brand\":\"Hyundai\",\"model\":\"Accent\",\"price\":6703,\"comments\":\"urna\",\"createdAt\":2012},\n"
            + "{\"name\":\"congue\",\"distDriven\":138084,\"brand\":\"Buick\",\"model\":\"Park Avenue\",\"price\":6835,\"comments\":\"vestibulum velit\",\"createdAt\":2010},\n"
            + "{\"name\":\"donec pharetra\",\"distDriven\":62386,\"brand\":\"Mercedes-Benz\",\"model\":\"M-Class\",\"price\":5237,\"comments\":\"neque libero\",\"createdAt\":2016},\n"
            + "{\"name\":\"sed\",\"distDriven\":18690,\"brand\":\"Chrysler\",\"model\":\"Sebring\",\"price\":3408,\"comments\":\"augue\",\"createdAt\":2016},\n"
            + "{\"name\":\"vestibulum ac\",\"distDriven\":136160,\"brand\":\"Mercedes-Benz\",\"model\":\"W201\",\"price\":4965,\"comments\":\"amet eros\",\"createdAt\":2014},\n"
            + "{\"name\":\"quisque arcu\",\"distDriven\":28132,\"brand\":\"Dodge\",\"model\":\"Ram 2500\",\"price\":3123,\"comments\":\"odio justo\",\"createdAt\":2014},\n"
            + "{\"name\":\"ut blandit\",\"distDriven\":147902,\"brand\":\"Toyota\",\"model\":\"4Runner\",\"price\":4048,\"comments\":\"duis at\",\"createdAt\":2011},\n"
            + "{\"name\":\"non\",\"distDriven\":126535,\"brand\":\"BMW\",\"model\":\"5 Series\",\"price\":2912,\"comments\":\"cras in\",\"createdAt\":2013},\n"
            + "{\"name\":\"lacus\",\"distDriven\":144555,\"brand\":\"Mazda\",\"model\":\"B-Series\",\"price\":6353,\"comments\":\"ullamcorper\",\"createdAt\":2012},\n"
            + "{\"name\":\"pede\",\"distDriven\":131792,\"brand\":\"Volvo\",\"model\":\"S60\",\"price\":5776,\"comments\":\"lectus aliquam\",\"createdAt\":2011},\n"
            + "{\"name\":\"neque\",\"distDriven\":103264,\"brand\":\"Saturn\",\"model\":\"Ion\",\"price\":2477,\"comments\":\"tempus vel\",\"createdAt\":2018},\n"
            + "{\"name\":\"vivamus vestibulum\",\"distDriven\":56215,\"brand\":\"BMW\",\"model\":\"525\",\"price\":6582,\"comments\":\"pellentesque viverra\",\"createdAt\":2012},\n"
            + "{\"name\":\"quam fringilla\",\"distDriven\":38736,\"brand\":\"Dodge\",\"model\":\"Ram 2500\",\"price\":4190,\"comments\":\"quam pharetra\",\"createdAt\":2013},\n"
            + "{\"name\":\"eleifend donec\",\"distDriven\":19295,\"brand\":\"Pontiac\",\"model\":\"Grand Prix\",\"price\":3540,\"comments\":\"potenti\",\"createdAt\":2018},\n"
            + "{\"name\":\"cubilia curae\",\"distDriven\":107102,\"brand\":\"Cadillac\",\"model\":\"Seville\",\"price\":3214,\"comments\":\"sit amet\",\"createdAt\":2018},\n"
            + "{\"name\":\"ultricies eu\",\"distDriven\":90116,\"brand\":\"GMC\",\"model\":\"Sonoma\",\"price\":5723,\"comments\":\"in\",\"createdAt\":2019},\n"
            + "{\"name\":\"tincidunt eget\",\"distDriven\":7483,\"brand\":\"Volvo\",\"model\":\"XC60\",\"price\":366,\"comments\":\"donec odio\",\"createdAt\":2013},\n"
            + "{\"name\":\"vestibulum rutrum\",\"distDriven\":131414,\"brand\":\"Chevrolet\",\"model\":\"Silverado\",\"price\":2620,\"comments\":\"nulla\",\"createdAt\":2011},\n"
            + "{\"name\":\"eros\",\"distDriven\":98100,\"brand\":\"Chevrolet\",\"model\":\"Express\",\"price\":3099,\"comments\":\"aliquam\",\"createdAt\":2018},\n"
            + "{\"name\":\"lectus aliquam\",\"distDriven\":137753,\"brand\":\"Chevrolet\",\"model\":\"Malibu\",\"price\":1362,\"comments\":\"odio porttitor\",\"createdAt\":2015},\n"
            + "{\"name\":\"odio\",\"distDriven\":120179,\"brand\":\"Mazda\",\"model\":\"Familia\",\"price\":6795,\"comments\":\"dictumst\",\"createdAt\":2013},\n"
            + "{\"name\":\"diam vitae\",\"distDriven\":71908,\"brand\":\"Bentley\",\"model\":\"Mulsanne\",\"price\":1688,\"comments\":\"vitae\",\"createdAt\":2013},\n"
            + "{\"name\":\"tortor eu\",\"distDriven\":84662,\"brand\":\"Volkswagen\",\"model\":\"Golf\",\"price\":4440,\"comments\":\"phasellus sit\",\"createdAt\":2012},\n"
            + "{\"name\":\"dictumst etiam\",\"distDriven\":41572,\"brand\":\"Chevrolet\",\"model\":\"Equinox\",\"price\":3472,\"comments\":\"hac\",\"createdAt\":2015},\n"
            + "{\"name\":\"proin interdum\",\"distDriven\":11530,\"brand\":\"Ford\",\"model\":\"Excursion\",\"price\":3102,\"comments\":\"sapien\",\"createdAt\":2016},\n"
            + "{\"name\":\"eget eros\",\"distDriven\":20627,\"brand\":\"Chevrolet\",\"model\":\"TrailBlazer\",\"price\":3710,\"comments\":\"justo\",\"createdAt\":2018},\n"
            + "{\"name\":\"pellentesque ultrices\",\"distDriven\":103174,\"brand\":\"Lexus\",\"model\":\"ES\",\"price\":6168,\"comments\":\"suspendisse accumsan\",\"createdAt\":2018},\n"
            + "{\"name\":\"erat\",\"distDriven\":92230,\"brand\":\"Ford\",\"model\":\"Mustang\",\"price\":6303,\"comments\":\"venenatis\",\"createdAt\":2019},\n"
            + "{\"name\":\"morbi sem\",\"distDriven\":32550,\"brand\":\"Ford\",\"model\":\"Crown Victoria\",\"price\":4413,\"comments\":\"in\",\"createdAt\":2016},\n"
            + "{\"name\":\"penatibus\",\"distDriven\":27326,\"brand\":\"Suzuki\",\"model\":\"SJ\",\"price\":452,\"comments\":\"dolor\",\"createdAt\":2010},\n"
            + "{\"name\":\"rutrum\",\"distDriven\":3089,\"brand\":\"Mitsubishi\",\"model\":\"Sigma\",\"price\":1429,\"comments\":\"nulla\",\"createdAt\":2013},\n"
            + "{\"name\":\"massa\",\"distDriven\":140206,\"brand\":\"Dodge\",\"model\":\"Caravan\",\"price\":3154,\"comments\":\"vestibulum\",\"createdAt\":2011},\n"
            + "{\"name\":\"venenatis non\",\"distDriven\":71283,\"brand\":\"Maserati\",\"model\":\"Karif\",\"price\":5197,\"comments\":\"penatibus et\",\"createdAt\":2011},\n"
            + "{\"name\":\"sapien\",\"distDriven\":97808,\"brand\":\"Honda\",\"model\":\"CR-V\",\"price\":6349,\"comments\":\"nulla nunc\",\"createdAt\":2019},\n"
            + "{\"name\":\"nulla sed\",\"distDriven\":40012,\"brand\":\"Ford\",\"model\":\"Club Wagon\",\"price\":1877,\"comments\":\"nam ultrices\",\"createdAt\":2014},\n"
            + "{\"name\":\"lacus purus\",\"distDriven\":132260,\"brand\":\"Mercedes-Benz\",\"model\":\"SLK-Class\",\"price\":5649,\"comments\":\"pretium\",\"createdAt\":2016},\n"
            + "{\"name\":\"varius\",\"distDriven\":149437,\"brand\":\"Plymouth\",\"model\":\"Reliant\",\"price\":1591,\"comments\":\"placerat ante\",\"createdAt\":2010},\n"
            + "{\"name\":\"ligula\",\"distDriven\":64406,\"brand\":\"Mitsubishi\",\"model\":\"Outlander\",\"price\":743,\"comments\":\"maecenas\",\"createdAt\":2017},\n"
            + "{\"name\":\"ut\",\"distDriven\":96627,\"brand\":\"Mitsubishi\",\"model\":\"Space\",\"price\":1556,\"comments\":\"lorem quisque\",\"createdAt\":2017},\n"
            + "{\"name\":\"enim lorem\",\"distDriven\":13107,\"brand\":\"Volkswagen\",\"model\":\"Scirocco\",\"price\":3495,\"comments\":\"mauris viverra\",\"createdAt\":2014},\n"
            + "{\"name\":\"at turpis\",\"distDriven\":134223,\"brand\":\"Mazda\",\"model\":\"MX-5\",\"price\":4722,\"comments\":\"dapibus augue\",\"createdAt\":2010},\n"
            + "{\"name\":\"sem fusce\",\"distDriven\":149717,\"brand\":\"Kia\",\"model\":\"Optima\",\"price\":2140,\"comments\":\"tellus in\",\"createdAt\":2012},\n"
            + "{\"name\":\"vestibulum sagittis\",\"distDriven\":65459,\"brand\":\"Volkswagen\",\"model\":\"Passat\",\"price\":5986,\"comments\":\"ante\",\"createdAt\":2015},\n"
            + "{\"name\":\"pede\",\"distDriven\":145528,\"brand\":\"Mercedes-Benz\",\"model\":\"E-Class\",\"price\":2640,\"comments\":\"dapibus nulla\",\"createdAt\":2016},\n"
            + "{\"name\":\"lectus in\",\"distDriven\":106552,\"brand\":\"Nissan\",\"model\":\"Altima\",\"price\":1985,\"comments\":\"platea\",\"createdAt\":2014},\n"
            + "{\"name\":\"in\",\"distDriven\":62356,\"brand\":\"Chevrolet\",\"model\":\"Corsica\",\"price\":5196,\"comments\":\"enim\",\"createdAt\":2010},\n"
            + "{\"name\":\"eget congue\",\"distDriven\":118797,\"brand\":\"Ford\",\"model\":\"LTD Crown Victoria\",\"price\":442,\"comments\":\"sit amet\",\"createdAt\":2014},\n"
            + "{\"name\":\"vulputate elementum\",\"distDriven\":6429,\"brand\":\"BMW\",\"model\":\"M5\",\"price\":2518,\"comments\":\"in\",\"createdAt\":2018},\n"
            + "{\"name\":\"sodales sed\",\"distDriven\":16230,\"brand\":\"Toyota\",\"model\":\"Camry\",\"price\":5379,\"comments\":\"maecenas\",\"createdAt\":2011},\n"
            + "{\"name\":\"interdum\",\"distDriven\":61711,\"brand\":\"Mazda\",\"model\":\"MPV\",\"price\":1644,\"comments\":\"lorem\",\"createdAt\":2018},\n"
            + "{\"name\":\"rutrum nulla\",\"distDriven\":85704,\"brand\":\"Chevrolet\",\"model\":\"G-Series G10\",\"price\":2281,\"comments\":\"ligula\",\"createdAt\":2018},\n"
            + "{\"name\":\"praesent\",\"distDriven\":132234,\"brand\":\"Mercury\",\"model\":\"Grand Marquis\",\"price\":1352,\"comments\":\"dui\",\"createdAt\":2012},\n"
            + "{\"name\":\"massa\",\"distDriven\":8226,\"brand\":\"Dodge\",\"model\":\"Charger\",\"price\":2035,\"comments\":\"nunc proin\",\"createdAt\":2017},\n"
            + "{\"name\":\"eget nunc\",\"distDriven\":107039,\"brand\":\"Chrysler\",\"model\":\"Sebring\",\"price\":2564,\"comments\":\"rutrum\",\"createdAt\":2019},\n"
            + "{\"name\":\"erat\",\"distDriven\":127320,\"brand\":\"Mazda\",\"model\":\"B-Series\",\"price\":4978,\"comments\":\"est lacinia\",\"createdAt\":2017},\n"
            + "{\"name\":\"dictumst morbi\",\"distDriven\":94491,\"brand\":\"Volkswagen\",\"model\":\"GTI\",\"price\":2816,\"comments\":\"vestibulum\",\"createdAt\":2019},\n"
            + "{\"name\":\"non lectus\",\"distDriven\":31283,\"brand\":\"Chevrolet\",\"model\":\"Metro\",\"price\":958,\"comments\":\"vel ipsum\",\"createdAt\":2012},\n"
            + "{\"name\":\"ac\",\"distDriven\":38346,\"brand\":\"Ford\",\"model\":\"Lightning\",\"price\":682,\"comments\":\"sit amet\",\"createdAt\":2011},\n"
            + "{\"name\":\"iaculis congue\",\"distDriven\":101548,\"brand\":\"Infiniti\",\"model\":\"Q\",\"price\":3700,\"comments\":\"duis at\",\"createdAt\":2013},\n"
            + "{\"name\":\"ipsum\",\"distDriven\":83306,\"brand\":\"Mazda\",\"model\":\"Mazda6\",\"price\":257,\"comments\":\"vestibulum\",\"createdAt\":2016},\n"
            + "{\"name\":\"dictumst morbi\",\"distDriven\":53838,\"brand\":\"Volvo\",\"model\":\"C30\",\"price\":6777,\"comments\":\"maecenas\",\"createdAt\":2016},\n"
            + "{\"name\":\"vulputate luctus\",\"distDriven\":13894,\"brand\":\"Jaguar\",\"model\":\"XJ Series\",\"price\":2798,\"comments\":\"lobortis\",\"createdAt\":2011},\n"
            + "{\"name\":\"vel\",\"distDriven\":143584,\"brand\":\"Volkswagen\",\"model\":\"Eurovan\",\"price\":4325,\"comments\":\"nascetur ridiculus\",\"createdAt\":2010},\n"
            + "{\"name\":\"integer non\",\"distDriven\":25695,\"brand\":\"Suzuki\",\"model\":\"Swift\",\"price\":144,\"comments\":\"volutpat\",\"createdAt\":2010},\n"
            + "{\"name\":\"elit proin\",\"distDriven\":128776,\"brand\":\"Volkswagen\",\"model\":\"Golf\",\"price\":6197,\"comments\":\"accumsan tellus\",\"createdAt\":2014},\n"
            + "{\"name\":\"montes\",\"distDriven\":113466,\"brand\":\"Subaru\",\"model\":\"Forester\",\"price\":6627,\"comments\":\"lacus morbi\",\"createdAt\":2014},\n"
            + "{\"name\":\"lacus at\",\"distDriven\":121220,\"brand\":\"Volvo\",\"model\":\"S60\",\"price\":5817,\"comments\":\"erat vestibulum\",\"createdAt\":2017},\n"
            + "{\"name\":\"non pretium\",\"distDriven\":131618,\"brand\":\"Chevrolet\",\"model\":\"Malibu\",\"price\":1022,\"comments\":\"pellentesque\",\"createdAt\":2013},\n"
            + "{\"name\":\"eu tincidunt\",\"distDriven\":132830,\"brand\":\"Chevrolet\",\"model\":\"Silverado 1500\",\"price\":2790,\"comments\":\"diam\",\"createdAt\":2011},\n"
            + "{\"name\":\"nulla nisl\",\"distDriven\":53814,\"brand\":\"BMW\",\"model\":\"1 Series\",\"price\":1247,\"comments\":\"erat\",\"createdAt\":2015},\n"
            + "{\"name\":\"erat\",\"distDriven\":75163,\"brand\":\"MINI\",\"model\":\"Cooper Countryman\",\"price\":6079,\"comments\":\"eleifend pede\",\"createdAt\":2013},\n"
            + "{\"name\":\"pharetra magna\",\"distDriven\":84686,\"brand\":\"Jeep\",\"model\":\"Grand Cherokee\",\"price\":4396,\"comments\":\"quis\",\"createdAt\":2012},\n"
            + "{\"name\":\"diam\",\"distDriven\":59579,\"brand\":\"Ferrari\",\"model\":\"FF\",\"price\":5290,\"comments\":\"pellentesque at\",\"createdAt\":2011},\n"
            + "{\"name\":\"aliquam augue\",\"distDriven\":10420,\"brand\":\"Mitsubishi\",\"model\":\"Chariot\",\"price\":6082,\"comments\":\"elit\",\"createdAt\":2016},\n"
            + "{\"name\":\"nibh\",\"distDriven\":80557,\"brand\":\"Mazda\",\"model\":\"MPV\",\"price\":4157,\"comments\":\"vestibulum sed\",\"createdAt\":2012},\n"
            + "{\"name\":\"proin\",\"distDriven\":112869,\"brand\":\"Chrysler\",\"model\":\"Town & Country\",\"price\":4570,\"comments\":\"vitae nisl\",\"createdAt\":2019},\n"
            + "{\"name\":\"tincidunt ante\",\"distDriven\":106281,\"brand\":\"Toyota\",\"model\":\"MR2\",\"price\":4504,\"comments\":\"justo\",\"createdAt\":2010},\n"
            + "{\"name\":\"sit amet\",\"distDriven\":39055,\"brand\":\"Toyota\",\"model\":\"Avalon\",\"price\":2557,\"comments\":\"at diam\",\"createdAt\":2012},\n"
            + "{\"name\":\"erat nulla\",\"distDriven\":41796,\"brand\":\"Dodge\",\"model\":\"Intrepid\",\"price\":1412,\"comments\":\"suspendisse\",\"createdAt\":2016},\n"
            + "{\"name\":\"vulputate\",\"distDriven\":92252,\"brand\":\"Land Rover\",\"model\":\"Defender 90\",\"price\":6513,\"comments\":\"arcu\",\"createdAt\":2013},\n"
            + "{\"name\":\"integer ac\",\"distDriven\":109092,\"brand\":\"Honda\",\"model\":\"Accord\",\"price\":5041,\"comments\":\"ut erat\",\"createdAt\":2011},\n"
            + "{\"name\":\"porttitor id\",\"distDriven\":87104,\"brand\":\"Hyundai\",\"model\":\"Sonata\",\"price\":1321,\"comments\":\"ultrices\",\"createdAt\":2016},\n"
            + "{\"name\":\"blandit nam\",\"distDriven\":94378,\"brand\":\"Chevrolet\",\"model\":\"Silverado 3500\",\"price\":6592,\"comments\":\"ligula\",\"createdAt\":2012},\n"
            + "{\"name\":\"dui vel\",\"distDriven\":98727,\"brand\":\"Lexus\",\"model\":\"IS\",\"price\":920,\"comments\":\"in tempor\",\"createdAt\":2010},\n"
            + "{\"name\":\"interdum mauris\",\"distDriven\":27892,\"brand\":\"Chevrolet\",\"model\":\"Caprice\",\"price\":939,\"comments\":\"in\",\"createdAt\":2014},\n"
            + "{\"name\":\"quam\",\"distDriven\":107585,\"brand\":\"Ford\",\"model\":\"Mustang\",\"price\":1796,\"comments\":\"at\",\"createdAt\":2018},\n"
            + "{\"name\":\"at\",\"distDriven\":67023,\"brand\":\"Chevrolet\",\"model\":\"Corvette\",\"price\":3326,\"comments\":\"cum\",\"createdAt\":2015},\n"
            + "{\"name\":\"nascetur ridiculus\",\"distDriven\":81073,\"brand\":\"Honda\",\"model\":\"Odyssey\",\"price\":1490,\"comments\":\"dapibus\",\"createdAt\":2016},\n"
            + "{\"name\":\"tortor\",\"distDriven\":74523,\"brand\":\"Volvo\",\"model\":\"S90\",\"price\":3344,\"comments\":\"eleifend\",\"createdAt\":2014},\n"
            + "{\"name\":\"consequat nulla\",\"distDriven\":142521,\"brand\":\"Ford\",\"model\":\"Explorer Sport Trac\",\"price\":220,\"comments\":\"nullam\",\"createdAt\":2018},\n"
            + "{\"name\":\"vestibulum\",\"distDriven\":6558,\"brand\":\"Honda\",\"model\":\"del Sol\",\"price\":4748,\"comments\":\"dapibus\",\"createdAt\":2015},\n"
            + "{\"name\":\"nulla dapibus\",\"distDriven\":112765,\"brand\":\"Lotus\",\"model\":\"Esprit\",\"price\":4094,\"comments\":\"lacus\",\"createdAt\":2016},\n"
            + "{\"name\":\"lectus\",\"distDriven\":78584,\"brand\":\"Ford\",\"model\":\"Freestyle\",\"price\":3134,\"comments\":\"magnis dis\",\"createdAt\":2019},\n"
            + "{\"name\":\"vel lectus\",\"distDriven\":45883,\"brand\":\"GMC\",\"model\":\"Savana 3500\",\"price\":3005,\"comments\":\"nunc donec\",\"createdAt\":2018},\n"
            + "{\"name\":\"vulputate ut\",\"distDriven\":95855,\"brand\":\"Ford\",\"model\":\"F150\",\"price\":4502,\"comments\":\"sit\",\"createdAt\":2015},\n"
            + "{\"name\":\"in\",\"distDriven\":75744,\"brand\":\"Chevrolet\",\"model\":\"G-Series 2500\",\"price\":2474,\"comments\":\"aliquet maecenas\",\"createdAt\":2019},\n"
            + "{\"name\":\"luctus\",\"distDriven\":27889,\"brand\":\"Pontiac\",\"model\":\"Bonneville\",\"price\":5660,\"comments\":\"adipiscing lorem\",\"createdAt\":2014},\n"
            + "{\"name\":\"sed vel\",\"distDriven\":86737,\"brand\":\"Infiniti\",\"model\":\"FX\",\"price\":2582,\"comments\":\"tincidunt\",\"createdAt\":2016},\n"
            + "{\"name\":\"lectus\",\"distDriven\":49128,\"brand\":\"Volkswagen\",\"model\":\"GTI\",\"price\":1972,\"comments\":\"augue\",\"createdAt\":2016},\n"
            + "{\"name\":\"elit\",\"distDriven\":36992,\"brand\":\"Subaru\",\"model\":\"Leone\",\"price\":4906,\"comments\":\"faucibus orci\",\"createdAt\":2010},\n"
            + "{\"name\":\"tempus semper\",\"distDriven\":121098,\"brand\":\"Hyundai\",\"model\":\"Azera\",\"price\":4205,\"comments\":\"donec\",\"createdAt\":2013},\n"
            + "{\"name\":\"vestibulum vestibulum\",\"distDriven\":34951,\"brand\":\"Honda\",\"model\":\"Ridgeline\",\"price\":730,\"comments\":\"sagittis nam\",\"createdAt\":2012},\n"
            + "{\"name\":\"scelerisque\",\"distDriven\":56733,\"brand\":\"Mercury\",\"model\":\"Sable\",\"price\":921,\"comments\":\"turpis\",\"createdAt\":2014},\n"
            + "{\"name\":\"sapien non\",\"distDriven\":24589,\"brand\":\"Tesla\",\"model\":\"Roadster\",\"price\":763,\"comments\":\"ipsum praesent\",\"createdAt\":2012},\n"
            + "{\"name\":\"morbi ut\",\"distDriven\":117602,\"brand\":\"Chevrolet\",\"model\":\"Express 2500\",\"price\":6940,\"comments\":\"elementum\",\"createdAt\":2010},\n"
            + "{\"name\":\"tempus\",\"distDriven\":36351,\"brand\":\"Aptera\",\"model\":\"Typ-1\",\"price\":5076,\"comments\":\"platea\",\"createdAt\":2017},\n"
            + "{\"name\":\"semper sapien\",\"distDriven\":51339,\"brand\":\"Smart\",\"model\":\"Fortwo\",\"price\":3296,\"comments\":\"ut tellus\",\"createdAt\":2011},\n"
            + "{\"name\":\"in\",\"distDriven\":55128,\"brand\":\"Pontiac\",\"model\":\"6000\",\"price\":6573,\"comments\":\"dignissim vestibulum\",\"createdAt\":2011},\n"
            + "{\"name\":\"id mauris\",\"distDriven\":98419,\"brand\":\"Pontiac\",\"model\":\"GTO\",\"price\":3529,\"comments\":\"bibendum felis\",\"createdAt\":2015},\n"
            + "{\"name\":\"sed\",\"distDriven\":20464,\"brand\":\"Kia\",\"model\":\"Sportage\",\"price\":4649,\"comments\":\"integer tincidunt\",\"createdAt\":2010},\n"
            + "{\"name\":\"nulla suspendisse\",\"distDriven\":63429,\"brand\":\"Lexus\",\"model\":\"LX\",\"price\":3090,\"comments\":\"habitasse\",\"createdAt\":2019},\n"
            + "{\"name\":\"luctus et\",\"distDriven\":58421,\"brand\":\"Mitsubishi\",\"model\":\"Montero\",\"price\":5585,\"comments\":\"nullam porttitor\",\"createdAt\":2019},\n"
            + "{\"name\":\"pede justo\",\"distDriven\":22571,\"brand\":\"Chrysler\",\"model\":\"LHS\",\"price\":6307,\"comments\":\"congue\",\"createdAt\":2013},\n"
            + "{\"name\":\"justo pellentesque\",\"distDriven\":106012,\"brand\":\"Ford\",\"model\":\"Bronco\",\"price\":1319,\"comments\":\"vestibulum\",\"createdAt\":2016},\n"
            + "{\"name\":\"mattis egestas\",\"distDriven\":99477,\"brand\":\"Mazda\",\"model\":\"Mazda6\",\"price\":6065,\"comments\":\"non\",\"createdAt\":2013},\n"
            + "{\"name\":\"nulla\",\"distDriven\":145495,\"brand\":\"Chevrolet\",\"model\":\"Venture\",\"price\":4064,\"comments\":\"vel est\",\"createdAt\":2014},\n"
            + "{\"name\":\"sapien\",\"distDriven\":98537,\"brand\":\"Volvo\",\"model\":\"960\",\"price\":6730,\"comments\":\"in sagittis\",\"createdAt\":2011},\n"
            + "{\"name\":\"amet erat\",\"distDriven\":142802,\"brand\":\"Mazda\",\"model\":\"MX-6\",\"price\":4520,\"comments\":\"ac diam\",\"createdAt\":2014},\n"
            + "{\"name\":\"cursus urna\",\"distDriven\":82452,\"brand\":\"Mercedes-Benz\",\"model\":\"SLK-Class\",\"price\":644,\"comments\":\"mi pede\",\"createdAt\":2012},\n"
            + "{\"name\":\"at nunc\",\"distDriven\":90432,\"brand\":\"Mazda\",\"model\":\"Miata MX-5\",\"price\":1191,\"comments\":\"eget massa\",\"createdAt\":2017},\n"
            + "{\"name\":\"etiam pretium\",\"distDriven\":144791,\"brand\":\"Volvo\",\"model\":\"V70\",\"price\":3129,\"comments\":\"magna bibendum\",\"createdAt\":2014},\n"
            + "{\"name\":\"neque\",\"distDriven\":91491,\"brand\":\"Cadillac\",\"model\":\"XLR\",\"price\":3316,\"comments\":\"nisl aenean\",\"createdAt\":2016},\n"
            + "{\"name\":\"eget\",\"distDriven\":124478,\"brand\":\"BMW\",\"model\":\"745\",\"price\":3141,\"comments\":\"cubilia\",\"createdAt\":2015},\n"
            + "{\"name\":\"ac\",\"distDriven\":29986,\"brand\":\"Lincoln\",\"model\":\"Navigator\",\"price\":4745,\"comments\":\"viverra dapibus\",\"createdAt\":2015},\n"
            + "{\"name\":\"pede malesuada\",\"distDriven\":50667,\"brand\":\"Jeep\",\"model\":\"Liberty\",\"price\":3925,\"comments\":\"diam erat\",\"createdAt\":2012},\n"
            + "{\"name\":\"diam\",\"distDriven\":140484,\"brand\":\"Lincoln\",\"model\":\"LS\",\"price\":5387,\"comments\":\"diam erat\",\"createdAt\":2011},\n"
            + "{\"name\":\"justo maecenas\",\"distDriven\":123753,\"brand\":\"Audi\",\"model\":\"A8\",\"price\":1775,\"comments\":\"pulvinar\",\"createdAt\":2010},\n"
            + "{\"name\":\"vel\",\"distDriven\":65336,\"brand\":\"Mercedes-Benz\",\"model\":\"CLK-Class\",\"price\":6920,\"comments\":\"fringilla rhoncus\",\"createdAt\":2015},\n"
            + "{\"name\":\"nunc\",\"distDriven\":58709,\"brand\":\"Suzuki\",\"model\":\"Samurai\",\"price\":5583,\"comments\":\"habitasse platea\",\"createdAt\":2017},\n"
            + "{\"name\":\"mauris vulputate\",\"distDriven\":80506,\"brand\":\"Ford\",\"model\":\"Taurus\",\"price\":3719,\"comments\":\"ipsum primis\",\"createdAt\":2010},\n"
            + "{\"name\":\"amet\",\"distDriven\":85029,\"brand\":\"Kia\",\"model\":\"Optima\",\"price\":3323,\"comments\":\"nulla\",\"createdAt\":2011},\n"
            + "{\"name\":\"magna bibendum\",\"distDriven\":100893,\"brand\":\"Bentley\",\"model\":\"Mulsanne\",\"price\":6818,\"comments\":\"molestie lorem\",\"createdAt\":2010},\n"
            + "{\"name\":\"curabitur\",\"distDriven\":127732,\"brand\":\"Lincoln\",\"model\":\"Mark VIII\",\"price\":5225,\"comments\":\"cras in\",\"createdAt\":2011},\n"
            + "{\"name\":\"cursus\",\"distDriven\":140097,\"brand\":\"Mercedes-Benz\",\"model\":\"C-Class\",\"price\":3327,\"comments\":\"nisl venenatis\",\"createdAt\":2015},\n"
            + "{\"name\":\"laoreet\",\"distDriven\":94171,\"brand\":\"Ford\",\"model\":\"Escort ZX2\",\"price\":4024,\"comments\":\"phasellus\",\"createdAt\":2014},\n"
            + "{\"name\":\"nulla suscipit\",\"distDriven\":4562,\"brand\":\"Pontiac\",\"model\":\"Sunfire\",\"price\":6704,\"comments\":\"praesent\",\"createdAt\":2017},\n"
            + "{\"name\":\"proin\",\"distDriven\":129169,\"brand\":\"Ford\",\"model\":\"Taurus\",\"price\":5946,\"comments\":\"donec\",\"createdAt\":2018},\n"
            + "{\"name\":\"quisque erat\",\"distDriven\":40017,\"brand\":\"Chevrolet\",\"model\":\"Metro\",\"price\":3433,\"comments\":\"convallis\",\"createdAt\":2015},\n"
            + "{\"name\":\"rutrum\",\"distDriven\":78036,\"brand\":\"Pontiac\",\"model\":\"Parisienne\",\"price\":1958,\"comments\":\"vehicula consequat\",\"createdAt\":2018},\n"
            + "{\"name\":\"nunc vestibulum\",\"distDriven\":63529,\"brand\":\"Toyota\",\"model\":\"Matrix\",\"price\":5027,\"comments\":\"sagittis\",\"createdAt\":2011},\n"
            + "{\"name\":\"ultrices\",\"distDriven\":35670,\"brand\":\"Chevrolet\",\"model\":\"Monte Carlo\",\"price\":5677,\"comments\":\"in\",\"createdAt\":2012},\n"
            + "{\"name\":\"risus\",\"distDriven\":70640,\"brand\":\"Mitsubishi\",\"model\":\"Galant\",\"price\":5086,\"comments\":\"neque vestibulum\",\"createdAt\":2010},\n"
            + "{\"name\":\"ut\",\"distDriven\":109905,\"brand\":\"Ford\",\"model\":\"Mustang\",\"price\":1910,\"comments\":\"libero convallis\",\"createdAt\":2011},\n"
            + "{\"name\":\"volutpat quam\",\"distDriven\":31614,\"brand\":\"Lincoln\",\"model\":\"LS\",\"price\":180,\"comments\":\"eros\",\"createdAt\":2018},\n"
            + "{\"name\":\"rutrum\",\"distDriven\":66141,\"brand\":\"Scion\",\"model\":\"xB\",\"price\":4042,\"comments\":\"pede\",\"createdAt\":2019},\n"
            + "{\"name\":\"pede justo\",\"distDriven\":30717,\"brand\":\"Chevrolet\",\"model\":\"Express 2500\",\"price\":3107,\"comments\":\"non lectus\",\"createdAt\":2014},\n"
            + "{\"name\":\"enim\",\"distDriven\":109215,\"brand\":\"Toyota\",\"model\":\"Venza\",\"price\":5597,\"comments\":\"ac nibh\",\"createdAt\":2019},\n"
            + "{\"name\":\"scelerisque\",\"distDriven\":33960,\"brand\":\"Land Rover\",\"model\":\"Range Rover Sport\",\"price\":1968,\"comments\":\"pellentesque quisque\",\"createdAt\":2016},\n"
            + "{\"name\":\"diam erat\",\"distDriven\":117363,\"brand\":\"Chrysler\",\"model\":\"Sebring\",\"price\":5586,\"comments\":\"donec diam\",\"createdAt\":2011},\n"
            + "{\"name\":\"et\",\"distDriven\":80885,\"brand\":\"Cadillac\",\"model\":\"Catera\",\"price\":6801,\"comments\":\"eu\",\"createdAt\":2015},\n"
            + "{\"name\":\"nec sem\",\"distDriven\":900,\"brand\":\"Cadillac\",\"model\":\"Eldorado\",\"price\":3817,\"comments\":\"convallis nulla\",\"createdAt\":2010},\n"
            + "{\"name\":\"gravida\",\"distDriven\":56129,\"brand\":\"Audi\",\"model\":\"Coupe Quattro\",\"price\":4844,\"comments\":\"enim lorem\",\"createdAt\":2010},\n"
            + "{\"name\":\"semper\",\"distDriven\":64843,\"brand\":\"Mazda\",\"model\":\"Protege\",\"price\":1266,\"comments\":\"nulla\",\"createdAt\":2014},\n"
            + "{\"name\":\"consequat lectus\",\"distDriven\":73845,\"brand\":\"Lexus\",\"model\":\"LS\",\"price\":4138,\"comments\":\"vehicula condimentum\",\"createdAt\":2013},\n"
            + "{\"name\":\"in hac\",\"distDriven\":102059,\"brand\":\"Audi\",\"model\":\"A4\",\"price\":6322,\"comments\":\"parturient\",\"createdAt\":2011},\n"
            + "{\"name\":\"rhoncus aliquam\",\"distDriven\":139843,\"brand\":\"Ford\",\"model\":\"Escort\",\"price\":4363,\"comments\":\"et ultrices\",\"createdAt\":2016},\n"
            + "{\"name\":\"feugiat\",\"distDriven\":119276,\"brand\":\"Ford\",\"model\":\"Explorer\",\"price\":1836,\"comments\":\"erat\",\"createdAt\":2018},\n"
            + "{\"name\":\"sed accumsan\",\"distDriven\":25882,\"brand\":\"Mercury\",\"model\":\"Cougar\",\"price\":4294,\"comments\":\"convallis duis\",\"createdAt\":2012},\n"
            + "{\"name\":\"feugiat et\",\"distDriven\":90445,\"brand\":\"Suzuki\",\"model\":\"Daewoo Lacetti\",\"price\":931,\"comments\":\"pharetra magna\",\"createdAt\":2019},\n"
            + "{\"name\":\"duis\",\"distDriven\":25089,\"brand\":\"Ram\",\"model\":\"1500\",\"price\":2390,\"comments\":\"elementum nullam\",\"createdAt\":2014},\n"
            + "{\"name\":\"potenti in\",\"distDriven\":81167,\"brand\":\"Mitsubishi\",\"model\":\"Galant\",\"price\":1282,\"comments\":\"convallis nulla\",\"createdAt\":2012},\n"
            + "{\"name\":\"nec\",\"distDriven\":88247,\"brand\":\"Fairthorpe\",\"model\":\"Rockette\",\"price\":1032,\"comments\":\"quam\",\"createdAt\":2014},\n"
            + "{\"name\":\"malesuada in\",\"distDriven\":147871,\"brand\":\"Ford\",\"model\":\"Ranger\",\"price\":6167,\"comments\":\"dapibus augue\",\"createdAt\":2018},\n"
            + "{\"name\":\"cras\",\"distDriven\":53273,\"brand\":\"Mitsubishi\",\"model\":\"Outlander\",\"price\":267,\"comments\":\"primis\",\"createdAt\":2019},\n"
            + "{\"name\":\"mi\",\"distDriven\":104766,\"brand\":\"Mazda\",\"model\":\"B-Series Plus\",\"price\":3730,\"comments\":\"nonummy integer\",\"createdAt\":2012},\n"
            + "{\"name\":\"feugiat\",\"distDriven\":139213,\"brand\":\"Buick\",\"model\":\"Skyhawk\",\"price\":1694,\"comments\":\"cubilia\",\"createdAt\":2013},\n"
            + "{\"name\":\"lacus\",\"distDriven\":76096,\"brand\":\"BMW\",\"model\":\"760\",\"price\":3972,\"comments\":\"id\",\"createdAt\":2013},\n"
            + "{\"name\":\"eros viverra\",\"distDriven\":78470,\"brand\":\"Dodge\",\"model\":\"D150\",\"price\":4941,\"comments\":\"in\",\"createdAt\":2010},\n"
            + "{\"name\":\"blandit nam\",\"distDriven\":82770,\"brand\":\"Mitsubishi\",\"model\":\"Diamante\",\"price\":1544,\"comments\":\"amet sem\",\"createdAt\":2014},\n"
            + "{\"name\":\"gravida\",\"distDriven\":95066,\"brand\":\"Chevrolet\",\"model\":\"Astro\",\"price\":2176,\"comments\":\"rutrum\",\"createdAt\":2015},\n"
            + "{\"name\":\"quam pharetra\",\"distDriven\":77228,\"brand\":\"Saab\",\"model\":\"9-3\",\"price\":2681,\"comments\":\"elementum ligula\",\"createdAt\":2014},\n"
            + "{\"name\":\"tempor\",\"distDriven\":75523,\"brand\":\"Jeep\",\"model\":\"Compass\",\"price\":3850,\"comments\":\"odio\",\"createdAt\":2015},\n"
            + "{\"name\":\"ipsum\",\"distDriven\":15785,\"brand\":\"Lincoln\",\"model\":\"MKZ\",\"price\":3834,\"comments\":\"suspendisse accumsan\",\"createdAt\":2014},\n"
            + "{\"name\":\"sem duis\",\"distDriven\":90279,\"brand\":\"Porsche\",\"model\":\"928\",\"price\":3480,\"comments\":\"accumsan felis\",\"createdAt\":2015},\n"
            + "{\"name\":\"pretium\",\"distDriven\":108961,\"brand\":\"Ford\",\"model\":\"Probe\",\"price\":3108,\"comments\":\"mus\",\"createdAt\":2013},\n"
            + "{\"name\":\"molestie sed\",\"distDriven\":104172,\"brand\":\"Isuzu\",\"model\":\"VehiCROSS\",\"price\":5550,\"comments\":\"mattis\",\"createdAt\":2015},\n"
            + "{\"name\":\"id sapien\",\"distDriven\":58010,\"brand\":\"Buick\",\"model\":\"Roadmaster\",\"price\":2538,\"comments\":\"nulla\",\"createdAt\":2017},\n"
            + "{\"name\":\"eu\",\"distDriven\":149608,\"brand\":\"Cadillac\",\"model\":\"Eldorado\",\"price\":6399,\"comments\":\"rhoncus sed\",\"createdAt\":2018},\n"
            + "{\"name\":\"accumsan odio\",\"distDriven\":79297,\"brand\":\"Chevrolet\",\"model\":\"Blazer\",\"price\":4613,\"comments\":\"nulla dapibus\",\"createdAt\":2015},\n"
            + "{\"name\":\"tristique tortor\",\"distDriven\":49588,\"brand\":\"Chevrolet\",\"model\":\"Express 3500\",\"price\":1865,\"comments\":\"ipsum\",\"createdAt\":2011},\n"
            + "{\"name\":\"libero\",\"distDriven\":8476,\"brand\":\"Subaru\",\"model\":\"Legacy\",\"price\":1235,\"comments\":\"sapien placerat\",\"createdAt\":2016},\n"
            + "{\"name\":\"et\",\"distDriven\":144361,\"brand\":\"Ford\",\"model\":\"Explorer\",\"price\":2498,\"comments\":\"quis libero\",\"createdAt\":2019},\n"
            + "{\"name\":\"imperdiet\",\"distDriven\":40466,\"brand\":\"Mazda\",\"model\":\"B-Series\",\"price\":3383,\"comments\":\"molestie\",\"createdAt\":2018},\n"
            + "{\"name\":\"morbi\",\"distDriven\":123494,\"brand\":\"Nissan\",\"model\":\"Altima\",\"price\":2892,\"comments\":\"ipsum\",\"createdAt\":2011},\n"
            + "{\"name\":\"viverra diam\",\"distDriven\":58560,\"brand\":\"Pontiac\",\"model\":\"Sunfire\",\"price\":5583,\"comments\":\"vestibulum\",\"createdAt\":2019},\n"
            + "{\"name\":\"vel ipsum\",\"distDriven\":36833,\"brand\":\"Oldsmobile\",\"model\":\"Intrigue\",\"price\":6219,\"comments\":\"sed tristique\",\"createdAt\":2015},\n"
            + "{\"name\":\"nibh ligula\",\"distDriven\":49780,\"brand\":\"Oldsmobile\",\"model\":\"Alero\",\"price\":6156,\"comments\":\"lacus\",\"createdAt\":2014},\n"
            + "{\"name\":\"nisl venenatis\",\"distDriven\":12870,\"brand\":\"Oldsmobile\",\"model\":\"88\",\"price\":4782,\"comments\":\"lacinia sapien\",\"createdAt\":2014},\n"
            + "{\"name\":\"orci\",\"distDriven\":109625,\"brand\":\"Volkswagen\",\"model\":\"Passat\",\"price\":2722,\"comments\":\"sit amet\",\"createdAt\":2012},\n"
            + "{\"name\":\"ac\",\"distDriven\":1505,\"brand\":\"Pontiac\",\"model\":\"Grand Am\",\"price\":6118,\"comments\":\"dui\",\"createdAt\":2011},\n"
            + "{\"name\":\"gravida\",\"distDriven\":19009,\"brand\":\"Acura\",\"model\":\"TL\",\"price\":5534,\"comments\":\"turpis adipiscing\",\"createdAt\":2011},\n"
            + "{\"name\":\"bibendum\",\"distDriven\":147258,\"brand\":\"Kia\",\"model\":\"Sedona\",\"price\":6551,\"comments\":\"praesent\",\"createdAt\":2017},\n"
            + "{\"name\":\"est congue\",\"distDriven\":135972,\"brand\":\"Acura\",\"model\":\"TL\",\"price\":719,\"comments\":\"eget eros\",\"createdAt\":2010},\n"
            + "{\"name\":\"ultrices\",\"distDriven\":148936,\"brand\":\"GMC\",\"model\":\"Jimmy\",\"price\":3947,\"comments\":\"adipiscing elit\",\"createdAt\":2010},\n"
            + "{\"name\":\"orci\",\"distDriven\":48912,\"brand\":\"Ford\",\"model\":\"Explorer\",\"price\":5481,\"comments\":\"aliquam\",\"createdAt\":2015},\n"
            + "{\"name\":\"proin at\",\"distDriven\":49069,\"brand\":\"Ford\",\"model\":\"Mustang\",\"price\":3489,\"comments\":\"at velit\",\"createdAt\":2010},\n"
            + "{\"name\":\"viverra\",\"distDriven\":100156,\"brand\":\"Volkswagen\",\"model\":\"Eurovan\",\"price\":6744,\"comments\":\"vitae nisi\",\"createdAt\":2018},\n"
            + "{\"name\":\"convallis\",\"distDriven\":33010,\"brand\":\"Dodge\",\"model\":\"Caliber\",\"price\":4449,\"comments\":\"non\",\"createdAt\":2019},\n"
            + "{\"name\":\"vitae\",\"distDriven\":123594,\"brand\":\"Mitsubishi\",\"model\":\"Precis\",\"price\":1939,\"comments\":\"accumsan tellus\",\"createdAt\":2010},\n"
            + "{\"name\":\"orci vehicula\",\"distDriven\":64204,\"brand\":\"Maserati\",\"model\":\"Quattroporte\",\"price\":6272,\"comments\":\"ac\",\"createdAt\":2015},\n"
            + "{\"name\":\"massa id\",\"distDriven\":49917,\"brand\":\"Lincoln\",\"model\":\"MKT\",\"price\":5461,\"comments\":\"nisl nunc\",\"createdAt\":2015},\n"
            + "{\"name\":\"tristique\",\"distDriven\":23617,\"brand\":\"Jaguar\",\"model\":\"S-Type\",\"price\":6520,\"comments\":\"nunc\",\"createdAt\":2019},\n"
            + "{\"name\":\"blandit\",\"distDriven\":4281,\"brand\":\"Chevrolet\",\"model\":\"Corvette\",\"price\":3869,\"comments\":\"tortor\",\"createdAt\":2016},\n"
            + "{\"name\":\"pellentesque eget\",\"distDriven\":119771,\"brand\":\"Volkswagen\",\"model\":\"R32\",\"price\":323,\"comments\":\"elit\",\"createdAt\":2015},\n"
            + "{\"name\":\"eleifend quam\",\"distDriven\":28293,\"brand\":\"Ford\",\"model\":\"Econoline E350\",\"price\":1304,\"comments\":\"vel lectus\",\"createdAt\":2016},\n"
            + "{\"name\":\"vel\",\"distDriven\":105893,\"brand\":\"Lincoln\",\"model\":\"Town Car\",\"price\":6243,\"comments\":\"rhoncus sed\",\"createdAt\":2017},\n"
            + "{\"name\":\"quam pharetra\",\"distDriven\":115516,\"brand\":\"Ford\",\"model\":\"Taurus\",\"price\":2624,\"comments\":\"hac habitasse\",\"createdAt\":2010},\n"
            + "{\"name\":\"donec vitae\",\"distDriven\":86824,\"brand\":\"Lincoln\",\"model\":\"Continental\",\"price\":5254,\"comments\":\"praesent id\",\"createdAt\":2010},\n"
            + "{\"name\":\"purus phasellus\",\"distDriven\":131891,\"brand\":\"Dodge\",\"model\":\"Ram\",\"price\":6747,\"comments\":\"pellentesque\",\"createdAt\":2011},\n"
            + "{\"name\":\"sollicitudin mi\",\"distDriven\":18124,\"brand\":\"Mazda\",\"model\":\"MX-5\",\"price\":6470,\"comments\":\"dictumst etiam\",\"createdAt\":2010},\n"
            + "{\"name\":\"faucibus orci\",\"distDriven\":59002,\"brand\":\"BMW\",\"model\":\"X5\",\"price\":2923,\"comments\":\"amet\",\"createdAt\":2012},\n"
            + "{\"name\":\"ut ultrices\",\"distDriven\":120912,\"brand\":\"Lotus\",\"model\":\"Esprit Turbo\",\"price\":3416,\"comments\":\"erat fermentum\",\"createdAt\":2010},\n"
            + "{\"name\":\"condimentum neque\",\"distDriven\":56855,\"brand\":\"Volkswagen\",\"model\":\"Cabriolet\",\"price\":6590,\"comments\":\"amet\",\"createdAt\":2014},\n"
            + "{\"name\":\"lacus\",\"distDriven\":148561,\"brand\":\"Buick\",\"model\":\"Coachbuilder\",\"price\":1314,\"comments\":\"nulla\",\"createdAt\":2014},\n"
            + "{\"name\":\"mi\",\"distDriven\":4729,\"brand\":\"Mitsubishi\",\"model\":\"Galant\",\"price\":1492,\"comments\":\"leo odio\",\"createdAt\":2012},\n"
            + "{\"name\":\"tellus nisi\",\"distDriven\":13996,\"brand\":\"Volkswagen\",\"model\":\"Passat\",\"price\":6167,\"comments\":\"congue elementum\",\"createdAt\":2011},\n"
            + "{\"name\":\"in lacus\",\"distDriven\":137154,\"brand\":\"Volkswagen\",\"model\":\"Golf\",\"price\":2328,\"comments\":\"vestibulum aliquet\",\"createdAt\":2011},\n"
            + "{\"name\":\"vestibulum\",\"distDriven\":149482,\"brand\":\"Lexus\",\"model\":\"ES\",\"price\":5706,\"comments\":\"vestibulum aliquet\",\"createdAt\":2015},\n"
            + "{\"name\":\"pede justo\",\"distDriven\":68192,\"brand\":\"Mercury\",\"model\":\"Villager\",\"price\":6782,\"comments\":\"porttitor lacus\",\"createdAt\":2019},\n"
            + "{\"name\":\"quis\",\"distDriven\":47664,\"brand\":\"Chevrolet\",\"model\":\"Monte Carlo\",\"price\":3423,\"comments\":\"congue\",\"createdAt\":2019},\n"
            + "{\"name\":\"ultrices\",\"distDriven\":93208,\"brand\":\"Dodge\",\"model\":\"Ram Wagon B150\",\"price\":3265,\"comments\":\"amet sapien\",\"createdAt\":2011},\n"
            + "{\"name\":\"leo odio\",\"distDriven\":37062,\"brand\":\"Isuzu\",\"model\":\"VehiCROSS\",\"price\":3350,\"comments\":\"praesent id\",\"createdAt\":2012},\n"
            + "{\"name\":\"lorem quisque\",\"distDriven\":13395,\"brand\":\"Mercedes-Benz\",\"model\":\"S-Class\",\"price\":207,\"comments\":\"odio porttitor\",\"createdAt\":2013},\n"
            + "{\"name\":\"ut mauris\",\"distDriven\":11070,\"brand\":\"Toyota\",\"model\":\"Previa\",\"price\":2375,\"comments\":\"eu felis\",\"createdAt\":2015},\n"
            + "{\"name\":\"cras mi\",\"distDriven\":146724,\"brand\":\"Buick\",\"model\":\"Regal\",\"price\":985,\"comments\":\"dictumst aliquam\",\"createdAt\":2016},\n"
            + "{\"name\":\"dictumst etiam\",\"distDriven\":79913,\"brand\":\"Kia\",\"model\":\"Soul\",\"price\":4195,\"comments\":\"imperdiet sapien\",\"createdAt\":2011},\n"
            + "{\"name\":\"proin at\",\"distDriven\":88776,\"brand\":\"Mercury\",\"model\":\"Cougar\",\"price\":6240,\"comments\":\"in\",\"createdAt\":2014},\n"
            + "{\"name\":\"vel\",\"distDriven\":81631,\"brand\":\"Land Rover\",\"model\":\"LR4\",\"price\":909,\"comments\":\"duis\",\"createdAt\":2012},\n"
            + "{\"name\":\"tortor eu\",\"distDriven\":75809,\"brand\":\"GMC\",\"model\":\"2500 Club Coupe\",\"price\":5244,\"comments\":\"eu\",\"createdAt\":2016},\n"
            + "{\"name\":\"metus\",\"distDriven\":110825,\"brand\":\"Pontiac\",\"model\":\"GTO\",\"price\":377,\"comments\":\"nisl\",\"createdAt\":2010},\n"
            + "{\"name\":\"vulputate\",\"distDriven\":147514,\"brand\":\"Mercedes-Benz\",\"model\":\"SLK-Class\",\"price\":2794,\"comments\":\"vestibulum ante\",\"createdAt\":2011},\n"
            + "{\"name\":\"nunc\",\"distDriven\":27648,\"brand\":\"Dodge\",\"model\":\"Dakota\",\"price\":3849,\"comments\":\"odio\",\"createdAt\":2010},\n"
            + "{\"name\":\"molestie\",\"distDriven\":115821,\"brand\":\"Chevrolet\",\"model\":\"Vega\",\"price\":4103,\"comments\":\"curabitur\",\"createdAt\":2012},\n"
            + "{\"name\":\"sed lacus\",\"distDriven\":118210,\"brand\":\"Ford\",\"model\":\"Expedition\",\"price\":4438,\"comments\":\"pede posuere\",\"createdAt\":2015},\n"
            + "{\"name\":\"ultrices libero\",\"distDriven\":11033,\"brand\":\"Ford\",\"model\":\"Bronco\",\"price\":3546,\"comments\":\"quam turpis\",\"createdAt\":2018},\n"
            + "{\"name\":\"amet\",\"distDriven\":117958,\"brand\":\"Acura\",\"model\":\"RL\",\"price\":999,\"comments\":\"luctus et\",\"createdAt\":2017},\n"
            + "{\"name\":\"eget rutrum\",\"distDriven\":51267,\"brand\":\"Chevrolet\",\"model\":\"Express 1500\",\"price\":2991,\"comments\":\"vel augue\",\"createdAt\":2019},\n"
            + "{\"name\":\"integer pede\",\"distDriven\":93713,\"brand\":\"Land Rover\",\"model\":\"Range Rover\",\"price\":6263,\"comments\":\"ligula in\",\"createdAt\":2018},\n"
            + "{\"name\":\"vestibulum\",\"distDriven\":59145,\"brand\":\"Lincoln\",\"model\":\"Town Car\",\"price\":4766,\"comments\":\"consequat ut\",\"createdAt\":2015},\n"
            + "{\"name\":\"lacus\",\"distDriven\":144380,\"brand\":\"Plymouth\",\"model\":\"Laser\",\"price\":3490,\"comments\":\"habitasse platea\",\"createdAt\":2014},\n"
            + "{\"name\":\"ante\",\"distDriven\":147278,\"brand\":\"Ford\",\"model\":\"E250\",\"price\":5782,\"comments\":\"urna pretium\",\"createdAt\":2019},\n"
            + "{\"name\":\"dictumst maecenas\",\"distDriven\":40794,\"brand\":\"Mercedes-Benz\",\"model\":\"W201\",\"price\":6191,\"comments\":\"est et\",\"createdAt\":2010},\n"
            + "{\"name\":\"est risus\",\"distDriven\":108631,\"brand\":\"Ford\",\"model\":\"Econoline E250\",\"price\":6784,\"comments\":\"vulputate\",\"createdAt\":2014},\n"
            + "{\"name\":\"odio\",\"distDriven\":136473,\"brand\":\"GMC\",\"model\":\"Rally Wagon 3500\",\"price\":6492,\"comments\":\"convallis\",\"createdAt\":2014},\n"
            + "{\"name\":\"nulla\",\"distDriven\":98801,\"brand\":\"Mercury\",\"model\":\"Grand Marquis\",\"price\":6177,\"comments\":\"nunc proin\",\"createdAt\":2014},\n"
            + "{\"name\":\"consequat\",\"distDriven\":115026,\"brand\":\"Jeep\",\"model\":\"Grand Cherokee\",\"price\":6118,\"comments\":\"potenti in\",\"createdAt\":2017},\n"
            + "{\"name\":\"habitasse platea\",\"distDriven\":56968,\"brand\":\"Mitsubishi\",\"model\":\"Chariot\",\"price\":3750,\"comments\":\"interdum\",\"createdAt\":2015},\n"
            + "{\"name\":\"natoque penatibus\",\"distDriven\":55252,\"brand\":\"Chevrolet\",\"model\":\"Monza\",\"price\":3479,\"comments\":\"turpis\",\"createdAt\":2018},\n"
            + "{\"name\":\"nam nulla\",\"distDriven\":5120,\"brand\":\"Mercury\",\"model\":\"Monterey\",\"price\":2578,\"comments\":\"lacinia aenean\",\"createdAt\":2014},\n"
            + "{\"name\":\"id pretium\",\"distDriven\":31786,\"brand\":\"Hummer\",\"model\":\"H3\",\"price\":1963,\"comments\":\"vitae\",\"createdAt\":2011},\n"
            + "{\"name\":\"venenatis\",\"distDriven\":59421,\"brand\":\"Honda\",\"model\":\"Odyssey\",\"price\":5065,\"comments\":\"sodales\",\"createdAt\":2013},\n"
            + "{\"name\":\"nam congue\",\"distDriven\":86711,\"brand\":\"GMC\",\"model\":\"Canyon\",\"price\":2364,\"comments\":\"ipsum primis\",\"createdAt\":2016},\n"
            + "{\"name\":\"vel accumsan\",\"distDriven\":57793,\"brand\":\"Mercury\",\"model\":\"Mariner\",\"price\":729,\"comments\":\"luctus tincidunt\",\"createdAt\":2011},\n"
            + "{\"name\":\"ut\",\"distDriven\":86638,\"brand\":\"GMC\",\"model\":\"Savana 2500\",\"price\":2121,\"comments\":\"ipsum\",\"createdAt\":2018},\n"
            + "{\"name\":\"rhoncus sed\",\"distDriven\":22819,\"brand\":\"Nissan\",\"model\":\"370Z\",\"price\":4962,\"comments\":\"lacinia\",\"createdAt\":2014},\n"
            + "{\"name\":\"consequat morbi\",\"distDriven\":37397,\"brand\":\"Mercedes-Benz\",\"model\":\"GLK-Class\",\"price\":6452,\"comments\":\"nibh\",\"createdAt\":2011},\n"
            + "{\"name\":\"faucibus\",\"distDriven\":53161,\"brand\":\"BMW\",\"model\":\"6 Series\",\"price\":3746,\"comments\":\"eu massa\",\"createdAt\":2019},\n"
            + "{\"name\":\"orci\",\"distDriven\":33279,\"brand\":\"Maserati\",\"model\":\"Coupe\",\"price\":2849,\"comments\":\"nulla\",\"createdAt\":2011},\n"
            + "{\"name\":\"ligula in\",\"distDriven\":16412,\"brand\":\"Mitsubishi\",\"model\":\"Mirage\",\"price\":4467,\"comments\":\"massa donec\",\"createdAt\":2016}]";

    public static void main(String[] args) {
        DBFiller d = new DBFiller();
        d.makeCarData();
        d.makeLocationTimeData();
    }

    private void makeCarData() {
        Gson g = new Gson();
        CarsFacade cf = new CarsFacade();
        int startObj = 0;
        int endObj = 0;
        while (data.length() > endObj + 10) {
            startObj = data.indexOf("{\"name\":", startObj + 1);
            endObj = data.indexOf("\n", startObj + 1);
            String carString = data.substring(startObj, endObj - 1);
            System.out.println(carString);
            Cars c = g.fromJson(carString, Cars.class);
            cf.addCar(c);
        }
    }

    private void makeLocationTimeData() {

        CarsFacade cf = new CarsFacade();
        LocationsTime lT = new LocationsTime();
        LocationsTimeFacade lTF = new LocationsTimeFacade();
        Cars c = cf.getCarById(3);
        lT.setCarId(c);
        lT.setEndsAt(new Date(2019, 9, 20));
        lT.setId(1);
        lT.setStartsAt(new Date(2018, 12, 13));
        lT.setStatus("Under repair");
        lT.setName("Random");
        lT.setLocLatitude(55770198);
        lT.setLocLongitude(125107138);
        lTF.addLocationsTime(lT);
        
    }
}
